# Generated by Django 5.1.2 on 2024-10-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_menu_alter_wishlist_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='menu',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='date_plan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
