# Generated by Django 5.1.1 on 2024-10-27 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guest_quantity', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('notes', models.TextField(blank=True, max_length=255)),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.restaurantentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
