# Generated by Django 5.1.1 on 2024-10-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveentry',
            name='jumlah_tamu',
            field=models.IntegerField(default=0),
        ),
    ]
