# Generated by Django 5.1.1 on 2024-10-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_reserveentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveentry',
            name='guest_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reserveentry',
            name='time',
            field=models.TimeField(),
        ),
    ]
