# Generated by Django 5.1.1 on 2024-10-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_alter_reserveentry_guest_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveentry',
            name='confirmation',
            field=models.BooleanField(default=True),
        ),
    ]
