# Generated by Django 5.1.1 on 2024-10-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_reserveentry_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveentry',
            name='confirmation',
        ),
    ]
