# Generated by Django 5.1.1 on 2024-10-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_remove_reserveentry_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveentry',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
