# Generated by Django 5.1.1 on 2024-10-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_alter_reserveentry_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveentry',
            name='notes',
        ),
        migrations.AddField(
            model_name='reserveentry',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
