# Generated by Django 5.1.1 on 2024-10-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_remove_reserveentry_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveentry',
            old_name='additional_notes',
            new_name='notes',
        ),
    ]
