# Generated by Django 5.1.2 on 2024-10-22 05:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_resto', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
                ('range_harga', models.CharField(max_length=50)),
                ('jenis_kuliner', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_menu', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('image_url', models.URLField()),
                ('restaurants', models.ManyToManyField(to='admin_dashboard.restaurantentry')),
            ],
        ),
    ]
