# Generated by Django 5.1.2 on 2024-10-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuentry',
            name='restaurants',
            field=models.ManyToManyField(related_name='menus', to='admin_dashboard.restaurantentry'),
        ),
    ]
