# Generated by Django 5.1.1 on 2024-10-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_menuentry_id_alter_menuentry_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuentry',
            name='no',
        ),
    ]
