# Generated by Django 5.1.2 on 2024-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_menuentry_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantentry',
            name='lokasi',
        ),
        migrations.AddField(
            model_name='restaurantentry',
            name='alamat',
            field=models.TextField(default='Yogyakarta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantentry',
            name='keramaian_resto',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantentry',
            name='lokasi_resto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantentry',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantentry',
            name='suasana',
            field=models.CharField(default='Santai', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantentry',
            name='range_harga',
            field=models.IntegerField(),
        ),
    ]
