# Generated by Django 5.1.2 on 2024-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_remove_restaurantentry_lokasi_restaurantentry_alamat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantentry',
            name='lokasi_resto',
            field=models.CharField(max_length=10),
        ),
    ]
