# Generated by Django 5.1.2 on 2024-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_restaurantentry_lokasi_resto'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuentry',
            name='no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
