# Generated by Django 5.1.1 on 2024-10-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManganJogja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('nama_resto', models.CharField(max_length=255)),
            ],
        ),
    ]
