# Generated by Django 5.1.2 on 2024-10-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('reviews', '0004_remove_review_restaurant_delete_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.restaurantentry'),
            preserve_default=False,
        ),
    ]
