# Generated by Django 5.1.1 on 2024-10-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_takeaway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeawayorder',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='takeawayorderitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
